services:
  book-store:
    image: albert/book-store:1.0-SNAPSHOT
    volumes:
      - ./jwt:/jwt
    ports:
      - "8081:8081"
    environment:
      - MP_JWT_VERIFY_PUBLICKEY_LOCATION=/jwt/publicKey.pem

  authentication-server:
    image: albert/jwt:1.0-SNAPSHOT
    volumes:
      - ./jwt:/jwt
    ports:
      - "8082:8082"
    environment:
      - SMALLRYE_JWT_SIGN_KEY_LOCATION=/jwt/privateKey.pem
