# version: "3.8"

#Anchor | Alias
x-deploy: &deploy
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]

services:
  postgresdb:
    image: postgres:16.2-bullseye
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=my_db
    ports:
      - "5432:5432"
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    <<: *deploy

  # NOTE: inside the pgadmin, use the name of the postgres container, and not localhost
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.11.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    <<: *deploy

# docker-compose exec -it postgresdb bash -c "psql"